services:
  app_proxy:
      environment:
        APP_HOST: martim-wallos_web_1
        APP_PORT: 8080/tcp
        PROXY_AUTH_ADD: "false"
  web:
    image: bellamy/wallos:latest
    environment:
      TZ: 'Atlantic/Madeira'
    # Volumes store your data between container upgrades
    volumes:
      - './db:/var/www/html/db'
      - './logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped