version: "3.9"
services:
  app_proxy:
      environment:
        APP_HOST: martim-wallos_wallos_1
        APP_PORT: 8282
        PROXY_AUTH_ADD: "false"
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    environment:
      TZ: 'Atlantic/Madeira'
    # Volumes store your data between container upgrades
    volumes:
      - './db:/var/www/html/db'
      - './logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped